import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.css'
import React, { useState } from "react";


const Homepage = () => {
    const [audiostyle, setStyle] = useState(styles.audioPlayer);

    const changeStyle = () => {
        if (audiostyle==styles.audioPlayer){
        setStyle(styles.dropdownPlayer)};
        if (audiostyle==styles.dropdownPlayer){
        setStyle(styles.audioPlayer)}

    }
    const [content, Toggle] = useState(styles.CT007Content)
    const [TrackList, Drop] = useState(styles.songContainer)
    const [artwork, Slide] = useState(styles.artworkContainer)
    const [title, Darkmode] = useState(styles.releaseTitle)

    const openClose = () => {
        if (title==styles.releaseTitle){
            Darkmode(styles.releaseTitleClicked)};
        if (TrackList==styles.songContainer){
            Drop(styles.songContainerOpen)};
        if (content==styles.CT007Content){
            Toggle(styles.CT007ContentOpen)};
        if (artwork==styles.artworkContainer){
            Slide(styles.artworkContainerOpen)};

            // reverse
        
        if(TrackList==styles.songContainerOpen){
            Drop(styles.songContainer)};
        if (content==styles.CT007ContentOpen){
            Toggle(styles.CT007Content)};
        if (artwork==styles.artworkContainerOpen){
            Slide(styles.artworkContainer)};
        
        }
    

  return (
      <div className={styles.pageContainer}>
      <Head>
        <title>Cult Trip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
        {/* release 1 */}
          <div className={styles.Release}>
            <h2 className={title} onClick={openClose}>CT007
            
                <input id="navArrow" name="navArrow" className={styles.CT007toggle} type="checkbox"/>
                <label htmlFor="navArrow" className={styles.arrow} >&gt;</label>
               
            </h2>
            
            <content className={content}>
                <div className={TrackList}>
                    <div className={styles.trackContainer} onClick={changeStyle}>
                        <audio controls className={audiostyle} src="/TEX86.mp3">
                            {/* <source src="/TEX86.mp3" type = "audio/mpeg"/> */}
                        </audio>
                        
                        <div className={styles.trackText}>
                            <h4>You'll Never Get Rich</h4>
                        </div>
                        
                    </div>
                    <div className={styles.trackContainer}>
                        <audio controls className={audiostyle}>
                            <source src="" type = "audio/mpeg"/>
                        </audio>
                        <div className={styles.trackText}>
                                <h4>Death by Dole</h4>
                        </div>
                    </div>
                </div>
                <div className={artwork}>
                    <svg  src=""/>
                </div>
            </content>
          </div>
        {/* Release 2 */}
        <div className={styles.Release}>
            <h2 className={styles.releaseTitle}>CT006</h2>
            <content className={styles.CT006Content}>
                <div className={styles.songContainer}>
                    <div className={styles.trackContainer} onClick={changeStyle}>
                        <audio controls className={audiostyle} src="/TEX86.mp3">
                            {/* <source src="/TEX86.mp3" type = "audio/mpeg"/> */}
                        </audio>
                        
                        <div className={styles.trackText}>
                            <h4>Track One</h4>
                        </div>
                        
                    </div>
                    <div className={styles.trackContainer}>
                        <audio controls className={styles.audioPlayer}>
                            <source src="" type = "audio/mpeg"/>
                        </audio>
                        <div className={styles.trackText}>
                                <h4>Track Two</h4>
                        </div>
                    </div>
                </div>
                <div className={styles.artworkContainer}>
                    <svg  src=""/>
                </div>
            </content>
          </div>       
        {/*closed page container*/}
      </div>
     

  );

};

export default Homepage;